package org.mentha.utils.archimate.model.nodes.dsl

import org.mentha.utils.archimate.model._
import org.mentha.utils.archimate.model.nodes._
import org.mentha.utils.archimate.model.nodes.impl._
import org.mentha.utils.archimate.model.edges._
import org.mentha.utils.archimate.model.edges.impl._

@javax.annotation.Generated(Array("org.mentha.utils.archimate.model.generator$"))
object Physical {

  implicit class ImplicitEquipment(src: Equipment)(implicit val model: Model) {

    def `associated with`(dst: Concept): AssociationRelationship = _associated_with(src, dst)(model)

    def `composes`(dst: Junction): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Device): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Equipment): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Facility): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Grouping): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Node): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: SystemSoftware): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: TechnologyCollaboration): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: TechnologyInterface): CompositionRelationship = _composes(src, dst)(model)

    def `aggregates`(dst: Junction): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Device): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Equipment): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Facility): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Grouping): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Node): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: SystemSoftware): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: TechnologyCollaboration): AggregationRelationship = _aggregates(src, dst)(model)
    @derived def `aggregates`(dst: TechnologyInterface): AggregationRelationship = _aggregates(src, dst)(model)

    def `serves`(dst: Junction): ServingRelationship = _serves(src, dst)(model)
    def `serves`(dst: Grouping): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationComponent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationService): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessActor): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessRole): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessService): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Device): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Equipment): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Facility): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Node): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: SystemSoftware): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyService): ServingRelationship = _serves(src, dst)(model)

    def `specializes`(dst: Junction): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Device): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Equipment): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Facility): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Grouping): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Node): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: SystemSoftware): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: TechnologyCollaboration): SpecializationRelationship = _specializes(src, dst)(model)

    def `accesses`($0: AccessType) = new {
      def `of`(dst: Junction): AccessRelationship = _accesses_of(src, dst)($0)(model)
      def `of`(dst: Grouping): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Artifact): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: BusinessObject): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Contract): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: DataObject): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Material): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Representation): AccessRelationship = _accesses_of(src, dst)($0)(model)
    }

    def `triggers`(dst: Junction): TriggeringRelationship = _triggers(src, dst)(model)
    def `triggers`(dst: Grouping): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationComponent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationService): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessActor): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessRole): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessService): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: CommunicationNetwork): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Device): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: DistributionNetwork): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Equipment): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Facility): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Location): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Node): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Path): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: SystemSoftware): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyService): TriggeringRelationship = _triggers(src, dst)(model)

    def `flows`($0: String) = new {
      def `to`(dst: Junction): FlowRelationship = _flows_to(src, dst)($0)(model)
      def `to`(dst: Grouping): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationComponent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationService): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessActor): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessRole): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessService): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: CommunicationNetwork): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Device): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: DistributionNetwork): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Equipment): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Facility): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Location): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Node): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Path): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Product): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: SystemSoftware): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyService): FlowRelationship = _flows_to(src, dst)($0)(model)
    }

    def `assigned-to`(dst: Junction): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Artifact): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Grouping): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Material): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyEvent): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyFunction): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyInteraction): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyProcess): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessActor): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessEvent): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessFunction): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessInteraction): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessInterface): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessProcess): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessRole): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessService): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: Device): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: Equipment): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: Facility): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: Node): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: SystemSoftware): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyCollaboration): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyInterface): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyService): AssignmentRelationship = _assigned_to(src, dst)(model)

    def `influences`($0: String) = new {
      def `in`(dst: Junction): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Constraint): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Grouping): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Requirement): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Assessment): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Driver): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Goal): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Meaning): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Outcome): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Principle): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Value): InfluenceRelationship = _influences_in(src, dst)($0)(model)
    }

    def `reads`(dst: Junction): AccessRelationship = _reads(src, dst)(model)
    def `reads`(dst: Grouping): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Artifact): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: BusinessObject): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Contract): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: DataObject): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Material): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Representation): AccessRelationship = _reads(src, dst)(model)

    def `realizes`(dst: Junction): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Constraint): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Device): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Equipment): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Facility): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Grouping): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Node): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Requirement): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Resource): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: SystemSoftware): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: TechnologyCollaboration): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationCollaboration): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationComponent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationService): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessActor): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessRole): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessService): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Capability): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: CourseOfAction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Goal): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Outcome): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Principle): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyService): RealizationRelationship = _realizes(src, dst)(model)

    def `writes`(dst: Junction): AccessRelationship = _writes(src, dst)(model)
    def `writes`(dst: Grouping): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Artifact): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: BusinessObject): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Contract): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: DataObject): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Material): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Representation): AccessRelationship = _writes(src, dst)(model)

  }

  implicit class ImplicitFacility(src: Facility)(implicit val model: Model) {

    def `associated with`(dst: Concept): AssociationRelationship = _associated_with(src, dst)(model)

    def `composes`(dst: Junction): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Device): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Equipment): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Facility): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Grouping): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Node): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: SystemSoftware): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: TechnologyCollaboration): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: TechnologyInterface): CompositionRelationship = _composes(src, dst)(model)

    def `aggregates`(dst: Junction): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Device): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Equipment): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Facility): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Grouping): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Node): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: SystemSoftware): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: TechnologyCollaboration): AggregationRelationship = _aggregates(src, dst)(model)
    @derived def `aggregates`(dst: TechnologyInterface): AggregationRelationship = _aggregates(src, dst)(model)

    def `serves`(dst: Junction): ServingRelationship = _serves(src, dst)(model)
    def `serves`(dst: Grouping): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationComponent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationService): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessActor): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessRole): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessService): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Device): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Equipment): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Facility): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Node): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: SystemSoftware): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyService): ServingRelationship = _serves(src, dst)(model)

    def `specializes`(dst: Junction): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Device): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Equipment): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Facility): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Grouping): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Node): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: SystemSoftware): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: TechnologyCollaboration): SpecializationRelationship = _specializes(src, dst)(model)

    def `accesses`($0: AccessType) = new {
      def `of`(dst: Junction): AccessRelationship = _accesses_of(src, dst)($0)(model)
      def `of`(dst: Grouping): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Artifact): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: BusinessObject): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Contract): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: DataObject): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Material): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Representation): AccessRelationship = _accesses_of(src, dst)($0)(model)
    }

    def `triggers`(dst: Junction): TriggeringRelationship = _triggers(src, dst)(model)
    def `triggers`(dst: Grouping): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationComponent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationService): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessActor): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessRole): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessService): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: CommunicationNetwork): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Device): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: DistributionNetwork): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Equipment): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Facility): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Location): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Node): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Path): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: SystemSoftware): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyService): TriggeringRelationship = _triggers(src, dst)(model)

    def `flows`($0: String) = new {
      def `to`(dst: Junction): FlowRelationship = _flows_to(src, dst)($0)(model)
      def `to`(dst: Grouping): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationComponent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationService): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessActor): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessRole): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessService): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: CommunicationNetwork): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Device): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: DistributionNetwork): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Equipment): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Facility): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Location): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Node): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Path): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Product): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: SystemSoftware): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyService): FlowRelationship = _flows_to(src, dst)($0)(model)
    }

    def `assigned-to`(dst: Junction): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Artifact): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: BusinessActor): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Device): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Equipment): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Facility): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Grouping): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Node): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: SystemSoftware): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyCollaboration): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyEvent): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyFunction): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyInteraction): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: TechnologyProcess): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessEvent): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessFunction): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessInteraction): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessInterface): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessProcess): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessRole): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessService): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyInterface): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyService): AssignmentRelationship = _assigned_to(src, dst)(model)

    def `influences`($0: String) = new {
      def `in`(dst: Junction): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Constraint): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Grouping): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Requirement): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Assessment): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Driver): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Goal): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Meaning): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Outcome): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Principle): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Value): InfluenceRelationship = _influences_in(src, dst)($0)(model)
    }

    def `reads`(dst: Junction): AccessRelationship = _reads(src, dst)(model)
    def `reads`(dst: Grouping): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Artifact): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: BusinessObject): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Contract): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: DataObject): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Material): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Representation): AccessRelationship = _reads(src, dst)(model)

    def `realizes`(dst: Junction): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Constraint): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Device): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Equipment): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Facility): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Grouping): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Node): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Requirement): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Resource): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: SystemSoftware): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: TechnologyCollaboration): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationCollaboration): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationComponent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationService): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessActor): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessRole): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessService): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Capability): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: CourseOfAction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Goal): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Outcome): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Principle): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyService): RealizationRelationship = _realizes(src, dst)(model)

    def `writes`(dst: Junction): AccessRelationship = _writes(src, dst)(model)
    def `writes`(dst: Grouping): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Artifact): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: BusinessObject): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Contract): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: DataObject): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Material): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Representation): AccessRelationship = _writes(src, dst)(model)

  }

  implicit class ImplicitDistributionNetwork(src: DistributionNetwork)(implicit val model: Model) {

    def `associated with`(dst: Concept): AssociationRelationship = _associated_with(src, dst)(model)

    def `composes`(dst: Junction): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: DistributionNetwork): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Grouping): CompositionRelationship = _composes(src, dst)(model)

    def `aggregates`(dst: Junction): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: DistributionNetwork): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Equipment): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Facility): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Grouping): AggregationRelationship = _aggregates(src, dst)(model)
    @derived def `aggregates`(dst: Device): AggregationRelationship = _aggregates(src, dst)(model)
    @derived def `aggregates`(dst: Node): AggregationRelationship = _aggregates(src, dst)(model)
    @derived def `aggregates`(dst: SystemSoftware): AggregationRelationship = _aggregates(src, dst)(model)
    @derived def `aggregates`(dst: TechnologyCollaboration): AggregationRelationship = _aggregates(src, dst)(model)
    @derived def `aggregates`(dst: TechnologyInterface): AggregationRelationship = _aggregates(src, dst)(model)

    def `serves`(dst: Junction): ServingRelationship = _serves(src, dst)(model)
    def `serves`(dst: Grouping): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationComponent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: ApplicationService): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessActor): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessRole): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: BusinessService): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Device): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Equipment): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Facility): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: Node): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: SystemSoftware): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyCollaboration): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyEvent): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyFunction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyInteraction): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyInterface): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyProcess): ServingRelationship = _serves(src, dst)(model)
    @derived def `serves`(dst: TechnologyService): ServingRelationship = _serves(src, dst)(model)

    def `specializes`(dst: Junction): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: DistributionNetwork): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Grouping): SpecializationRelationship = _specializes(src, dst)(model)

    def `accesses`($0: AccessType) = new {
      def `of`(dst: Junction): AccessRelationship = _accesses_of(src, dst)($0)(model)
      def `of`(dst: Grouping): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Artifact): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: BusinessObject): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Contract): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: DataObject): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Material): AccessRelationship = _accesses_of(src, dst)($0)(model)
      @derived def `of`(dst: Representation): AccessRelationship = _accesses_of(src, dst)($0)(model)
    }

    def `triggers`(dst: Junction): TriggeringRelationship = _triggers(src, dst)(model)
    def `triggers`(dst: Grouping): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationComponent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: ApplicationService): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessActor): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessRole): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: BusinessService): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: CommunicationNetwork): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Device): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: DistributionNetwork): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Equipment): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Facility): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Location): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Node): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: Path): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: SystemSoftware): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyCollaboration): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyEvent): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyFunction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyInteraction): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyInterface): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyProcess): TriggeringRelationship = _triggers(src, dst)(model)
    @derived def `triggers`(dst: TechnologyService): TriggeringRelationship = _triggers(src, dst)(model)

    def `flows`($0: String) = new {
      def `to`(dst: Junction): FlowRelationship = _flows_to(src, dst)($0)(model)
      def `to`(dst: Grouping): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationComponent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: ApplicationService): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessActor): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessRole): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: BusinessService): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: CommunicationNetwork): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Device): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: DistributionNetwork): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Equipment): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Facility): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Location): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Node): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Path): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: Product): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: SystemSoftware): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyCollaboration): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyEvent): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyFunction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyInteraction): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyInterface): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyProcess): FlowRelationship = _flows_to(src, dst)($0)(model)
      @derived def `to`(dst: TechnologyService): FlowRelationship = _flows_to(src, dst)($0)(model)
    }

    def `assigned-to`(dst: Junction): AssignmentRelationship = _assigned_to(src, dst)(model)
    def `assigned-to`(dst: Grouping): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessActor): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessEvent): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessFunction): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessInteraction): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessInterface): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessProcess): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessRole): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: BusinessService): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: Device): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: Equipment): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: Facility): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: Node): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: SystemSoftware): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyCollaboration): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyEvent): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyFunction): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyInteraction): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyInterface): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyProcess): AssignmentRelationship = _assigned_to(src, dst)(model)
    @derived def `assigned-to`(dst: TechnologyService): AssignmentRelationship = _assigned_to(src, dst)(model)

    def `influences`($0: String) = new {
      def `in`(dst: Junction): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Constraint): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Grouping): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Requirement): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Assessment): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Driver): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Goal): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Meaning): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Outcome): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Principle): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Value): InfluenceRelationship = _influences_in(src, dst)($0)(model)
    }

    def `reads`(dst: Junction): AccessRelationship = _reads(src, dst)(model)
    def `reads`(dst: Grouping): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Artifact): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: BusinessObject): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Contract): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: DataObject): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Material): AccessRelationship = _reads(src, dst)(model)
    @derived def `reads`(dst: Representation): AccessRelationship = _reads(src, dst)(model)

    def `realizes`(dst: Junction): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Constraint): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Grouping): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Path): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Requirement): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Resource): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationCollaboration): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationComponent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: ApplicationService): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessActor): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessRole): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: BusinessService): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Capability): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: CourseOfAction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Device): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Equipment): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Facility): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Goal): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Node): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Outcome): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Principle): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: SystemSoftware): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyCollaboration): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyEvent): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyFunction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyInteraction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyInterface): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyProcess): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: TechnologyService): RealizationRelationship = _realizes(src, dst)(model)

    def `writes`(dst: Junction): AccessRelationship = _writes(src, dst)(model)
    def `writes`(dst: Grouping): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Artifact): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: BusinessObject): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Contract): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: DataObject): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Material): AccessRelationship = _writes(src, dst)(model)
    @derived def `writes`(dst: Representation): AccessRelationship = _writes(src, dst)(model)

  }

  implicit class ImplicitMaterial(src: Material)(implicit val model: Model) {

    def `associated with`(dst: Concept): AssociationRelationship = _associated_with(src, dst)(model)

    def `composes`(dst: Junction): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Grouping): CompositionRelationship = _composes(src, dst)(model)
    def `composes`(dst: Material): CompositionRelationship = _composes(src, dst)(model)

    def `aggregates`(dst: Junction): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Grouping): AggregationRelationship = _aggregates(src, dst)(model)
    def `aggregates`(dst: Material): AggregationRelationship = _aggregates(src, dst)(model)

    def `specializes`(dst: Junction): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Grouping): SpecializationRelationship = _specializes(src, dst)(model)
    def `specializes`(dst: Material): SpecializationRelationship = _specializes(src, dst)(model)

    def `influences`($0: String) = new {
      def `in`(dst: Junction): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Constraint): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Grouping): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      def `in`(dst: Requirement): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Assessment): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Driver): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Goal): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Meaning): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Outcome): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Principle): InfluenceRelationship = _influences_in(src, dst)($0)(model)
      @derived def `in`(dst: Value): InfluenceRelationship = _influences_in(src, dst)($0)(model)
    }

    def `realizes`(dst: Junction): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: BusinessObject): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Constraint): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Contract): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Grouping): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Requirement): RealizationRelationship = _realizes(src, dst)(model)
    def `realizes`(dst: Resource): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Capability): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: CourseOfAction): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Goal): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Outcome): RealizationRelationship = _realizes(src, dst)(model)
    @derived def `realizes`(dst: Principle): RealizationRelationship = _realizes(src, dst)(model)

  }
}
